# Generated by Django 3.1.6 on 2021-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
