# Generated by Django 3.1.6 on 2021-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycatApp', '0002_auto_20210209_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
