# Generated by Django 3.1.6 on 2021-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycatApp', '0004_auto_20210209_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cardnews',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
